package postgres

import (
	"context"
	"testing"
	"time"

	"github.com/hoanghonghuy/synfactory/internal/domain"
	"github.com/hoanghonghuy/synfactory/internal/workflow"
)

func TestWorkflowDispatchIsIdempotentAndConsumesBudgetOnce(t *testing.T){store:=openTestStore(t);repo:=seedRepository(t,store);ctx:=context.Background();stored,err:=store.UpsertWorkflow(ctx,workflow.NewInstance(repo.ID,workflow.KindIssue,"42","sha-1",120));if err!=nil{t.Fatal(err)};decision:=workflow.Decision{TargetState:workflow.StateVerifying,Reason:"CI failed",Action:&workflow.Action{Key:stored.ID+":ci:sha-1",Kind:workflow.ActionCIRepair,Mode:workflow.ActionJob,Role:domain.RoleCIGuardian,TargetState:workflow.StateVerifying,Budget:workflow.BudgetCIRepair,Priority:140,MaxAttempts:2}};job:=workflow.JobSpec{ID:"job-workflow-ci",DedupeKey:"workflow-ci-key",RepositoryID:repo.ID,Kind:"ci_repair",Role:domain.RoleCIGuardian,Subject:"42",Revision:"sha-1",Priority:140,MaxAttempts:2,AvailableAt:time.Now().Add(-time.Second)};first,dispatch,err:=store.DispatchAction(ctx,stored.ID,decision,job,domain.RoleCIGuardian,time.Now().UTC());if err!=nil||!dispatch.Dispatched||first.CIRepairAttempts!=1{t.Fatalf("first dispatch %+v %+v %v",first,dispatch,err)};second,dispatch,err:=store.DispatchAction(ctx,stored.ID,decision,job,domain.RoleCIGuardian,time.Now().UTC());if err!=nil||dispatch.Dispatched||second.CIRepairAttempts!=1{t.Fatalf("duplicate dispatch %+v %+v %v",second,dispatch,err)}}

func TestTaskReservationIsExclusiveRecoverableAndPermanentAfterBind(t *testing.T){store:=openTestStore(t);repo:=seedRepository(t,store);ctx:=context.Background();fp:=workflow.TaskFingerprint(repo.FullName,"feature","exclusive feature scope");now:=time.Now().UTC();reserved,err:=store.ReserveTask(ctx,repo.ID,fp,"pm-a",now,time.Minute);if err!=nil||!reserved{t.Fatalf("first reserve %v %v",reserved,err)};reserved,err=store.ReserveTask(ctx,repo.ID,fp,"pm-a",now.Add(10*time.Second),time.Minute);if err!=nil||!reserved{t.Fatalf("same owner retry must recover %v %v",reserved,err)};reserved,err=store.ReserveTask(ctx,repo.ID,fp,"pm-b",now.Add(20*time.Second),time.Minute);if err!=nil||reserved{t.Fatalf("other owner must not steal %v %v",reserved,err)};if err:=store.BindTask(ctx,repo.ID,fp,"pm-a",77,"open",now.Add(30*time.Second));err!=nil{t.Fatal(err)};reserved,err=store.ReserveTask(ctx,repo.ID,fp,"pm-c",now.Add(10*time.Minute),time.Minute);if err!=nil||reserved{t.Fatalf("bound task must dedupe permanently %v %v",reserved,err)}}

func TestNewRevisionResetsBlockedRepairBudget(t *testing.T){store:=openTestStore(t);repo:=seedRepository(t,store);ctx:=context.Background();instance:=workflow.NewInstance(repo.ID,workflow.KindIssue,"88","old",100);stored,err:=store.UpsertWorkflow(ctx,instance);if err!=nil{t.Fatal(err)};stored,err=store.ApplyDecision(ctx,stored.ID,workflow.Decision{TargetState:workflow.StateBlocked,BlockedReason:"ci_repair_budget_exhausted"},domain.RoleTeamLead,time.Now().UTC());if err!=nil{t.Fatal(err)};if _,err:=store.db.ExecContext(ctx,`UPDATE workflow_instances SET ci_repair_attempts=2,review_repair_attempts=2 WHERE id=$1`,stored.ID);err!=nil{t.Fatal(err)};instance.Revision="new";fresh,err:=store.UpsertWorkflow(ctx,instance);if err!=nil{t.Fatal(err)};if fresh.State!=workflow.StateDiscovered||fresh.CIRepairAttempts!=0||fresh.ReviewRepairAttempts!=0||fresh.BlockedReason!=""{t.Fatalf("revision did not recover workflow %+v",fresh)}}
